# Generated by Django 2.0 on 2019-06-28 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='username',
        ),
        migrations.RemoveField(
            model_name='person',
            name='email_id',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='email_id',
        ),
        migrations.AddField(
            model_name='login',
            name='email',
            field=models.EmailField(default=True, max_length=254),
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(default=True, max_length=254),
        ),
        migrations.AddField(
            model_name='registration',
            name='email',
            field=models.EmailField(default=True, max_length=254),
        ),
    ]
