# Generated by Django 2.0 on 2019-06-28 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190628_1043'),
    ]

    operations = [
        migrations.DeleteModel(
            name='person',
        ),
    ]
