# Generated by Django 2.0 on 2019-07-02 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_delete_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='Password',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='password',
        ),
    ]
